### ISSUE TITLE
Configuration of API via YAML file

### ISSUE THREAD

**Issue by Spedge** [specialedge/hangar-api#2]
We want to be able to configure the API - basic configurations may be around the storage path, but in the future we may want to start up the API in different modes (simple, ephemeral etc).

Something along these lines?

```
storage:
  type: local
  path: '/data'

index:
  type: in-memory
```
